# This file is documentation/archive, but beware the real source of truth is https://hpanel.hostinger.com/vps/780680/docker-manager/compose/traefik-cpag/edit

services:
  traefik:
    image: traefik:latest
    restart: unless-stopped
    networks:
      - traefik-proxy
    ports:
      - "80:80"
      - "443:443"
    environment:
      # Stored in .env file in hostinger GUI (also redunndantly stored in github secrets, but not read at time of writing)
      - HOSTINGER_API_TOKEN=${HOSTINGER_API_TOKEN}
    command:
      - --api.dashboard=false
      - --api.insecure=false
      - --log.level=INFO
      - --providers.docker=true
      - --providers.docker.network=traefik-proxy
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.letsencrypt.acme.httpchallenge=true
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.letsencrypt-wildcard.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt-wildcard.acme.dnschallenge.provider=hostinger
      # Stored in .env file in hostinger GUI
      - --certificatesresolvers.letsencrypt-wildcard.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.letsencrypt-wildcard.acme.storage=/letsencrypt/acme.json
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
    volumes:
      - traefik-letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  traefik-letsencrypt:


networks:
  traefik-proxy:
    name: traefik-proxy
