name: development

on:
  push:
    branches:
      - 'f[0-9]+-*'
    paths-ignore: 
      - '**/.gitignore'
      - '**/README.md'

jobs:
  extract:
    runs-on: self-hosted
    outputs:
      target_domain: ${{ steps.extract.outputs.target_domain }}
      my_github_issue_id: ${{ steps.extract.outputs.my_github_issue_id }}
    steps:
    - name: Extract target_domain from branch
      id: extract
      run: |
        my_github_issue_id=$(echo "${{ github.ref_name }}" | sed -E 's/^f([0-9]+)-.*/\1/')
        if [ -z "$my_github_issue_id" ] || ! [[ "$my_github_issue_id" =~ ^[0-9]+$ ]]; then
          echo "Error: Invalid branch name format"
          exit 1
        fi
        echo "my_github_issue_id=${my_github_issue_id}" >> $GITHUB_OUTPUT
        echo "target_domain=${my_github_issue_id}.dev.veiledprofits.com" >> $GITHUB_OUTPUT
  setup_persistence_dir:
    runs-on: self-hosted
    needs: extract
    outputs:
      persistence_dir: ${{ steps.clone.outputs.persistence_dir }}
    steps:
    - name: Copy and Scrub
      id: clone 
      run: |
        ISSUE_ID="${{ needs.extract.outputs.my_github_issue_id }}"
        rm -rf /srv/dev/$ISSUE_ID/stl-meetings/data
        rm -rf /srv/dev/$ISSUE_ID/stl-permits/data
        rm -rf /srv/dev/$ISSUE_ID/mo-permits/data
        mkdir -p /srv/dev/$ISSUE_ID/stl-meetings/data
        mkdir -p /srv/dev/$ISSUE_ID/stl-permits/data
        mkdir -p /srv/dev/$ISSUE_ID/mo-permits/data
        cp -R /root/stl-meetings/data /srv/dev/$ISSUE_ID/stl-meetings/
        cp -R /root/stl-permits/data  /srv/dev/$ISSUE_ID/stl-permits/
        cp -R /root/mo-permits/data   /srv/dev/$ISSUE_ID/mo-permits/
        which sqlite3 || sudo apt-get install -y sqlite3
        sqlite3 /srv/dev/$ISSUE_ID/stl-meetings/data/meetings.db "DELETE FROM subscribers;"
        sqlite3 /srv/dev/$ISSUE_ID/stl-permits/data/permits.db   "DELETE FROM subscribers;"
        sqlite3 /srv/dev/$ISSUE_ID/mo-permits/data/permits.db    "DELETE FROM subscribers;"
        echo "persistence_dir=/srv/dev/$ISSUE_ID" >> $GITHUB_OUTPUT
      # TODO: Populate Secrets
  build:
    needs: 
      - extract
      - setup_persistence_dir
    uses: ./.github/workflows/deploy.yml
    with:
      environment: development
      environment_nickname: "dev-${{ needs.extract.outputs.my_github_issue_id }}"
      target_domain: ${{ needs.extract.outputs.target_domain }}
      persistence_dir: ${{ needs.setup_persistence_dir.outputs.persistence_dir }}
    secrets: inherit