name: Docker Image CI

on:
  workflow_dispatch:
  push:
    #branches: [ "main" ]
    branches: [ "condensing_docker_compose" ]
    paths-ignore: 
      - '.github/**'
      - '.gitignore'
      - '.editorconfig'
      - '.LICENSE.md'
      - 'README.md'
  pull_request:
    branches: [ "condensing_docker_compose" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Build the Docker image
    #need to check that these containers do spin up like they are supposed to,
    #and that this is all the containers we need to run
      run: docker compose up --build --detach
      #as to how to run docker compose to get it to do everything that I want

      
