name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths-ignore: 
      '.github/**'
      '.gitignore'
      '.editorconfig'
      '.LICENSE.md'
      'README.md'
      '**docker-compose.yml'
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -name: Checkout repository
    - uses: actions/checkout@v4
    - name: Build the Docker image
    #need to check that these containers do spin up like they are supposed to,
    #and that this is all the containers we need to run
      run: docker build . --file Dockerfile --tag mo-permits-app:$(date +%s)
      run: docker build . --file Dockerfile --tag stl-permits-app:$(date +%s)
      run: docker build . --file Dockerfile --tag mo-meetings-app:$(date +%s)
      run: docker build . --file Dockerfile --tag mo-permits-app:$(date +%s)
      
