name: production

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths-ignore: 
      - '**/.gitignore'
      - '**/README.md'

jobs:
  build:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production
      target_domain: veiledprofits.com
      persistence_dir: /root
    secrets: inherit